### ISSUE TITLE
Support of s3fs with dependencies

### ISSUE THREAD

**Issue by mbrhd** [aws-samples/smallmatter-package#22]
I'm trying to export plots of training results to the output folder like in your [gluonts example](https://github.com/aws-samples/amazon-sagemaker-gluonts-entrypoint/tree/main/notebooks)

Config is as follows:

Estimator: `MXNet`
framework_version: `1.6.0`
Requirements.txt file: 

```
gluonts==0.7.6
mxnet>=1.6.0,<1.8.0
pandas>=1.0,<1.1
git+https://github.com/aws-samples/amazon-sagemaker-entrypoint-utilities@v0.1.0#egg=smepu
git+https://github.com/aws-samples/smallmatter-package@v0.1.0#egg=smallmatter[all]
```
I'm getting this error at s3fs import when calling `from smallmatter.ds import MontagePager`

```
Traceback (most recent call last):
  File "trainer.py", line 20, in <module>
    from evaluator import MyEvaluator
  File "/opt/ml/code/evaluator.py", line 10, in <module>
    from smallmatter.ds import MontagePager
  File "/usr/local/lib/python3.6/site-packages/smallmatter/ds.py", line 16, in <module>
    from .pathlib import Path2, pathify
  File "/usr/local/lib/python3.6/site-packages/smallmatter/pathlib.py", line 21, in <module>
    import s3fs
  File "/usr/local/lib/python3.6/site-packages/s3fs/__init__.py", line 1, in <module>
    from .core import S3FileSystem, S3File
  File "/usr/local/lib/python3.6/site-packages/s3fs/core.py", line 18, in <module>
    import aiobotocore.session
  File "/usr/local/lib/python3.6/site-packages/aiobotocore/session.py", line 6, in <module>
    from .client import AioClientCreator, AioBaseClient
  File "/usr/local/lib/python3.6/site-packages/aiobotocore/client.py", line 11, in <module>
    from .paginate import AioPaginator
  File "/usr/local/lib/python3.6/site-packages/aiobotocore/paginate.py", line 7, in <module>
    import aioitertools
  File "/usr/local/lib/python3.6/site-packages/aioitertools/__init__.py", line 9, in <module>
    from . import asyncio
  File "/usr/local/lib/python3.6/site-packages/aioitertools/asyncio.py", line 26, in <module>
    from .builtins import iter as aiter, maybe_await
  File "/usr/local/lib/python3.6/site-packages/aioitertools/builtins.py", line 33, in <module>
    from .helpers import maybe_await, Orderable
  File "/usr/local/lib/python3.6/site-packages/aioitertools/helpers.py", line 8, in <module>
    from .types import T
  File "/usr/local/lib/python3.6/site-packages/aioitertools/types.py", line 18, in <module>
    from typing_extensions import ParamSpec
```

**Comment by verdimrc** [comment]
Hi, might be caused by incompatible versions among `s3fs`, `aiobotocore`, and `aiohttp`.

Could try adding to `requirements.txt` these entries (which are taken from the latest s3fs version):

```txt
s3fs==2022.8.2
aiobotocore~=2.4.0
fsspec==2022.8.2
aiohttp!=4.0.0a0, !=4.0.0a1
```

and if the issue persists, could you share part of the training logs related to the `pip install -r requirements.txt`? Thanks.

**Comment by mbrhd** [comment]
Hi @verdimrc 

Thanks a lot for the support. I fixed it by adding
```
typing-extensions==4.1.1
```
to my `requirements.txt` file. It is, in fact, incompatibility versions among s3fs, aiobotocore, and aiohttp.

Thanks
